BMARGIN: &BMARGIN 10

bar:
  height: 30
  location: top
  background: 191919e6
  foreground: ffffffbb
  font: Noto Sans CJK JP:Bold:size=13,Font Awesome 6 Free:style=solid:size=13
  right-margin: *BMARGIN
  layer: bottom
  left:
    -
      script:
        path: /home/donovan/.config/yambar/hyprland.sh
        args: []
        content:
          string:
            on-click:
              left: sh -c 'hyprctl dispatch workspace e+1'
              right: sh -c 'hyprctl dispatch workspace empty'
              middle: sh -c 'kitty ranger ~'
            text: "{hypr_ws}"
            left-margin: *BMARGIN
  center:
    -
      foreign-toplevel:
        content:
          map:
            conditions:
              ~activated: {empty: {}}
              activated:
                - string: {text: "{title}", max: 90, on-click: 'notify-send "app-id" "{app-id}"'}
  right:
    -
      battery:
        name: BAT0
        anchors:
          discharging: &discharging
            list:
              items:
                - ramp:
                    tag: capacity
                    items:
                      - string: {text: , foreground: ff0000ff}
                      - string: {text: , foreground: ffa600ff}
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: }
                      - string: {text: , foreground: 00ff00ff}
                - string: {text: "{capacity}% {estimate}", left-margin: *BMARGIN}
        content:
          map:
            conditions:
              state == unknown:
                <<: *discharging
              state == discharging:
                <<: *discharging
              state == charging:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: "{capacity}% {estimate}"}
              state == full:
                - string: {text: , foreground: 00ff00ff}
                - string: {text: "{capacity}% full"}
              state == "not charging":
                - ramp:
                    tag: capacity
                    items:
                      - string: {text:  , foreground: ff0000ff}
                      - string: {text:  , foreground: ffa600ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                      - string: {text:  , foreground: 00ff00ff}
                - string: {text: "{capacity}%"}
    -
      clock:
        time-format: "%H:%M %Z"
        content:
          - string: {text: , right-margin: 5, left-margin: *BMARGIN}
          - string: {text: "{date}", on-click: 'yad --calendar --title "今日は何の日"'}
          - string: {text: , right-margin: 5, left-margin: *BMARGIN}
          - string: {text: "{time}"}
    -
      label:
        content:
          string:
            on-click: sh -c 'rofi -show'
            text: 
            left-margin: *BMARGIN
